# WPP TO TAKE INPUT BASE AND HEIGHT OF THE TRIANGLE AND PRINT THE AREA OF THE TRIANGLE

base = int(input('ENTER THE BASE OF THE TRIANGLE :'))
height = int(input('ENTER THE HEIGHT OF THE TRIANGLE :'))
print('AREA IS : ', 0.5 * height * base)
